# Start from UBI9 image
FROM registry.access.redhat.com/ubi9/ubi:9.5-1730489303

# Set work directory
WORKDIR /root

# DNF install packages either from repo or locally
RUN dnf install wget procps-ng pciutils yum jq iputils ethtool net-tools -y

# Cleanup 
WORKDIR /root
RUN dnf clean all

# Run container entrypoint
COPY entrypoint.sh /root/entrypoint.sh
ENTRYPOINT ["/bin/bash", "/root/entrypoint.sh"]
#CMD ["there"]
